name: Run pipeline

on:
  schedule:
    # every day at 2:15am UTC (change as needed)
    - cron: "15 2 * * *"
  workflow_dispatch:  # lets you run it manually from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install 
                             pip install pyyaml

      - name: Run pipeline
        env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
         # SMTP_PASS:     ${{ secrets.SMTP_PASS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          python dedupe_pipeline.py
